### ISSUE TITLE
Naps

### ISSUE THREAD

**Issue by kaihendry** [hackerspacesg/KGB#2]

**Comment by icedwater** [comment]
More details are needed for the resolution of this issue. Is napping unsightly? Should it only be allowed in certain areas? At particular times? How do we align this with live-and-let-work?

**Comment by rolandturner** [comment]
Per my earlier comments (and discussions right back to founding), I 
reiterate my strong objection to people sleeping in the space.

HackerspaceSG need not - and should not - look like a corporate office, 
but it also shouldn't look like a college dorm room. It should be a 
welcoming place for people to visit and congregate, which is not at all 
compatible with having people sleeping in the space.

- Roland

**Comment by hyperair** [comment]
Due to the fantastic one-word bug and 0-char description, I'll just draw my own conclusions and think that Kai wants there to be more napping in HackerspaceSG. Let's have a siesta time of 3 hours after lunch daily where napping will be compulsory.

**Comment by GIANTCRAB** [comment]
Closing this, please re-open if we still need to discuss about having compulsory napping times. Thanks!

**Comment by icedwater** [comment]
I agree with @rolandturner in principle. We should make the space as welcoming as possible.

However, should one happen to be hacking on something past 3am, I think having a snooze before public transport reopens, or breakfast, or etc is quite reasonable, as long as the space is cleaned up before, e.g. 10am on weekends or 8am on weekdays.
