### ISSUE TITLE
RIPE Atlas Probe

### ISSUE THREAD

**Issue by GIANTCRAB** [hackerspacesg/KGB#24]
I've re-flashed the old probe multiple times with a new USB and despite showing DNS probes, it was not able to download the firmware successfully. I've applied for a new probe on Jan 4 2022. However, due to global chip shortage, the new HSG probe is still on the wait-list.

**Comment by valentine** [comment]
Discussion from [2022-05-24 plenum](https://docs.hackerspace.sg/plenum/2022-05-24/):

> - Huiren: still pending reply on new probe due to global chip shortage

**Comment by GIANTCRAB** [comment]
Update on probe:

```
Dear Huiren Woo,

Your RIPE Atlas probe order has been confirmed.


The probe will be shipped to this address:
Huiren Woo
336D King George’s Avenue None
208572 Singapore
SG



Shipment
We use the Dutch postal service, and it is not possible to track the shipment. Depending on the destination, it normally takes one to six weeks to ship the package. Once the probe has shipped, you will receive a confirmation email.

So sit back and relax. We hope that you receive your probe soon, and we look forward to seeing that new vantage point blinking from your network.
```

**Comment by GIANTCRAB** [comment]
> We are happy to let you know that your probe has been shipped on 2022-11-10 10:58 UTC

```
--- Shipping information ---
For single package we use Dutch postal (postnl) which is not traceable.
Below is the duration of the delivery time from the moment you receive this email:
Western Europe: 1-2 weeks
Rest of Europe: 2-4 week.
Rest of the world: 2-6 weeks
```

**Comment by GIANTCRAB** [comment]
I set it up with the user tag "hackerspace" and now the probe is live on https://atlas.ripe.net/probes/61023/
