### ISSUE TITLE
Cleaning up after eating

### ISSUE THREAD

**Issue by valentine** [hackerspacesg/KGB#3]
This is happening again.

Quote from [a topic](https://groups.google.com/d/msg/hackerspacesg/F-5pvu75ytw/MXU1mWX5qcEJ) on our mailing list:

> Hi all
> 
> If you guys, gals and children open your eyes and take a careful look
> around hackerspace, you will notice that this place is fast becoming a
> pig sty. In fact, I think some pigs have better living environment
> than us. (Apologies to our Muslim members. Sorry, I seriously cannot
> find another name for it other than pig sty)
> 
> I know I have been nagging about this again and again. But have to
> repeat myself again. Can everyone please be more responsible when you
> are in Hackerspace? As far as I know, there is only 1 rule in
> Hackerspace, that is to clean up after use. But it seems to me that
> many people are not following this one simple rule. And the
> responsibility does not end after you throw your rubbish into the
> dustbin. Someone need to empty the dustbin. I know some of you have
> also been emptying the dustbin everytime they come to hackerspace. But
> the responsible people aren't able to come to hackerspace every single
> day. Everyone need to play their part to keep the place clean.
> 
> We are still having lots of ants in hackerspace despite the fact that
> we gotten lots of ant poison. I think the poison alone is not going to
> work if everyone don't maintain cleanliness here. And if we don't do
> something about this, I think we will start to have roaches and event
> rats someday. Seriously everyone. PLEASE wake up, do something before
> we need to hire professional pest busters.
> 
> After drinking, please rinse your cup and put it on top of the
> dishwasher. I've lost count on the number of times I find cup on
> tables. The cups on the dishwasher does not have legs. Someone needs
> to put them in the dishwasher and turn on the dishwasher every once in
> a while. When the dishwasher finish its job, someone needs to empty
> them before the whole dishwasher stink like a sewage. Seriously, I
> think I can teach my 7 year old nephew to do all these. I don't think
> we have any members that is still in primary school.
> 
> The table are always full of things. If you have to leave things in
> hackerspace, please put them in the cardboard. If they are too bulky,
> then please put them in an orderly manner before you leave.
> 
> And the ice maker in the fridge. For goodness sake, the fridge we got
> does not have an automatic ice maker. SOMEONE needs to refill the
> water in order to make ice. Do we have to put another freaking label
> on the fridge to TEACH all of you to do this?
> 
> I keep saying that all the labels in hackerspace are a huge disgrace
> to the members here. Some of the instructions (like the 1 on the
> toilet bowl) are COMMON SENSE! I have no idea why the heck we need
> those labels. Even kids know that they are suppose to clean the toilet
> bowl after use if there are stain. WHY is it that the members of
> hackerspace need a label to remind them something that little kids
> know since primary school? Are we all adults here? Is there any sense
> of responsibilities here? Are we treating Hackerspace like a public
> place or a home?
> 
> I hope this is going to be the last time I need to bring up this issue
> on google group. We are all adults. Please behave like one.
> 
> PS: I know some of you have been very responsible and keeping the
> place clean. Thank you. This posting is for those who aren't.

**Comment by GIANTCRAB** [comment]
Resolved with #14
