### ISSUE TITLE
Move oven to dishwasher area; install shelf

### ISSUE THREAD

**Issue by valentine** [hackerspacesg/KGB#4]
The oven is presently situated in the air-conditioned open space, near two air-con units. This is counterproductive to both cooling and heating up food.

It might be better to:
1. Install a shelf (with L-mounts or other appropriate fixtures) next to the dishwasher.
2. Move oven and other similar heating devices there.

Ideally, we will hire someone to perform the installation. This requires $$.

**Comment by notthetup** [comment]
Good idea. This will also affect the smell in the space when someone cooks or accidentally over-cooks something. Why would we need to hire someone to install a shelf?

**Comment by Valentine** [comment]
@notthetup: The same reason we had someone install the cupboards above the television: I'm slightly skeptical about whether us hackers can do it properly, since it might have to bear a significant amount of weight.

Also, who's going to volunteer to do it?

**Comment by notthetup** [comment]
Volunteer part is a good point. If you're looking at a shelf for the oven, I think the weight can be calculated. I'd say most IKEA L-brackets should suffice. The oven isn't THAT heavy.

**Comment by robertsky** [comment]
well, we have the projector mounted by ourselves. As for the proposed
location, i recommend putting above the electric stove instead as the top
of the dishwasher is currently used to place cutleries pending for the next
dishwashing cycle.

**Comment by rolandturner** [comment]
Standard bookshelf brackets will suffice. Find a load/length chart for 
screws and plugs, or just drill deeper holes and use long ones.

- Roland
