### ISSUE TITLE
Countering unpleasant smells

### ISSUE THREAD

**Issue by valentine** [hackerspacesg/KGB#5]
I've been thinking about this for a while. This seems to make sense to counter food odours, at least. I know some of us have been [boiling orange/lemon peels](http://www.ehow.com/how_12077471_make-room-deodorizer-out-oranges.html) at times, but that freshens the air, not deodourises it.

There's a bunch of [air purifiers on Gumtree](http://singapore.gumtree.sg/p/Classifieds/sharp-air-purifier?CatId=0&isSearchForm=true), both new and used, for under $200. 

Note that these aren't the cheap China knockoffs. I have a Sharp at home (also purchased used on Gumtree), and it does an impressive job in keeping my room in a liveable condition.

I think it might be a good idea to purchase one first and see how effective it is (without regard for actual room size). If anything, it'll provide _slightly_ fresher air for us anyway.

**Comment by notthetup** [comment]
Another (not mutually exclusive) way could to be to open all the windows and doors one of the evenings when it's windy outside (and turn off the aircon of course). I do that at home. I agree it's a lot more involved, but something if we can do once in a while it should help.

**Comment by robertsky** [comment]
@Chinmay,

I do that almost every weekend, but the smell still lingers on. Hence
Valentine's suggestion.

Robert

**Comment by elfgoh** [comment]
Any chance we can borrow @Valentine 's air purifier and put it on trial for less than 24 hours to gauge if it is effective?

**Comment by Valentine** [comment]
@elfgoh If you (or anyone else) is willing to help me transport it from my home and back, sure! I believe the dimensions are 57.2cm x 41.6cm x 24.1cm and weighs around 9kg.

**Comment by GIANTCRAB** [comment]
Closing this as we have move to a new place. Please re-open if this persists, thanks!
